# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab6-lsriw/Lab6-lsriw.srcs/sources_1/ip/c_add/c_add.xci
# IP: The module: 'c_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/SR/BodziochKonrad/SR/Lab6-lsriw/Lab6-lsriw.gen/sources_1/ip/c_add/c_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab6-lsriw/Lab6-lsriw.srcs/sources_1/ip/c_add/c_add.xci
# IP: The module: 'c_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/SR/BodziochKonrad/SR/Lab6-lsriw/Lab6-lsriw.gen/sources_1/ip/c_add/c_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
