# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab10/hdmi_vga_zybo_downgraded/hdmi_vga_zybo_downgraded.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab10/hdmi_vga_zybo_downgraded/hdmi_vga_zybo_downgraded.gen/sources_1/ip/rgb2ycbcr_0/src/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab10/hdmi_vga_zybo_downgraded/hdmi_vga_zybo_downgraded.gen/sources_1/ip/rgb2ycbcr_0/src/c_add/c_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_add || ORIG_REF_NAME==c_add} -quiet] -quiet

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab10/hdmi_vga_zybo_downgraded/hdmi_vga_zybo_downgraded.gen/sources_1/ip/rgb2ycbcr_0/src/c_add2/c_add2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_add2 || ORIG_REF_NAME==c_add2} -quiet] -quiet

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab10/hdmi_vga_zybo_downgraded/hdmi_vga_zybo_downgraded.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab10/hdmi_vga_zybo_downgraded/hdmi_vga_zybo_downgraded.gen/sources_1/ip/rgb2ycbcr_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab10/hdmi_vga_zybo_downgraded/hdmi_vga_zybo_downgraded.gen/sources_1/ip/rgb2ycbcr_0/src/c_add/c_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_add || ORIG_REF_NAME==c_add} -quiet] -quiet

# IP: /home/lsriw/SR/BodziochKonrad/SR/Lab10/hdmi_vga_zybo_downgraded/hdmi_vga_zybo_downgraded.gen/sources_1/ip/rgb2ycbcr_0/src/c_add2/c_add2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_add2 || ORIG_REF_NAME==c_add2} -quiet] -quiet
