# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dunge/Desktop/Systemy Rekonfigurowalne/Lab6/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/c_add/c_add.xci
# IP: The module: 'c_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dunge/Desktop/Systemy Rekonfigurowalne/Lab6/rgb2ycbcr/rgb2ycbcr.gen/sources_1/ip/c_add/c_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/dunge/Desktop/Systemy Rekonfigurowalne/Lab6/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/c_add/c_add.xci
# IP: The module: 'c_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dunge/Desktop/Systemy Rekonfigurowalne/Lab6/rgb2ycbcr/rgb2ycbcr.gen/sources_1/ip/c_add/c_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
